import streamlit as st
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# -------------------------
# 1. 建 toy dataset（之後可改成你自己的資料）
# -------------------------
def get_demo_dataset():
    ai_texts = [
        "This article discusses the key factors that influence customer satisfaction in modern online platforms.",
        "In conclusion, the experimental results demonstrate significant improvements compared with baseline models.",
        "The following paragraph was generated by an advanced language model trained on a large corpus of text.",
        "Overall, this report provides an overview of potential applications and future research directions."
    ]

    human_texts = [
        "今天上完課之後，我回家慢慢整理老師講的重點，順便把作業的想法寫下來。",
        "昨天跟朋友去看電影，看完之後我們討論劇情討論到半夜，真的很好玩。",
        "我覺得學程式一開始很痛苦，但是慢慢理解之後會有一種解謎成功的成就感。",
        "寫報告的時候，常常會先打草稿，再慢慢修改成比較正式的版本。"
    ]

    texts = ai_texts + human_texts
    labels = [1] * len(ai_texts) + [0] * len(human_texts)   # 1 = AI, 0 = Human
    return texts, labels

# -------------------------
# 2. 訓練模型（用 cache，避免每次重新訓練）
# -------------------------
@st.cache_resource
def get_model():
    texts, labels = get_demo_dataset()

    vectorizer = TfidfVectorizer(
        ngram_range=(1, 2),
        max_features=5000,
        min_df=1
    )
    X = vectorizer.fit_transform(texts)

    clf = LogisticRegression(max_iter=1000)
    clf.fit(X, labels)

    return vectorizer, clf

vectorizer, clf = get_model()

# -------------------------
# 3. Streamlit UI
# -------------------------
st.set_page_config(page_title="AI / Human 文章偵測器", layout="wide")

st.title("Q1 — AI / Human 文章偵測器（AI Detector）")
st.write("輸入一段文字，我會幫你估計這段文字比較像 **AI** 寫的還是 **Human** 寫的。")

user_text = st.text_area("請輸入要分析的文字：", height=220)

if st.button("開始偵測"):

    if not user_text.strip():
        st.warning("請先輸入文字再按偵測～")
    else:
        X_input = vectorizer.transform([user_text])
        proba = clf.predict_proba(X_input)[0]  # [P(Human=0), P(AI=1)]
        ai_prob = float(proba[1])
        human_prob = float(proba[0])

        ai_percent = ai_prob * 100
        human_percent = human_prob * 100

        col1, col2 = st.columns(2)
        with col1:
            st.metric("AI %", f"{ai_percent:.1f}%")
        with col2:
            st.metric("Human %", f"{human_percent:.1f}%")

        st.write("---")
        st.subheader("機率視覺化")

        st.progress(ai_prob)
        st.caption("進度條越接近右邊，代表越像 AI 產生的文字。")

        st.bar_chart({
            "probability": [ai_prob, human_prob]
        })

        st.info("目前是示範模型，用小型資料集訓練。你可以在報告裡說明之後會加入更多樣本或更進階的模型。")
